global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'portfolio-app'
    static_configs:
      - targets: ['web:80']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']