name: Deploy to S3

on:
  push:
    branches:
      - master  # or main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Sync files to S3
        run: |
          ls -R ./dist
          aws s3 sync ./dist s3://godwin-devops \
            --delete \
            --acl public-read \
            --exclude ".github/*"